/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package at.timofeev.arcore.sessionRecorder;

public final class R {
    public static final class id {
        public static final int __arcore_cancelButton = 0x7f080006;
        public static final int __arcore_continueButton = 0x7f080007;
        public static final int __arcore_messageText = 0x7f080008;
    }
    public static final class layout {
        public static final int __arcore_education = 0x7f0a0000;
    }
    public static final class string {
        public static final int __arcore_cancel = 0x7f0b0000;
        public static final int __arcore_continue = 0x7f0b0001;
        public static final int __arcore_install_app = 0x7f0b0002;
        public static final int __arcore_install_feature = 0x7f0b0003;
        public static final int __arcore_installing = 0x7f0b0004;
    }
}
